version: '3'
services:

# server**
  web:
    container_name: docker_java
    build: ./server/demo
    restart: always
    ports:
      - '8080:8080'
    networks:
      - java-tier
# angular
  client:
    container_name: docker_angular
    build: ./client
    restart: always
    ports:
      - '4200:4200'
    networks:
      - angular-tier

networks:
  java-tier:
  angular-tier:
