
version: '3.2'
services:

# server**
  web:
    build: ./demo
    expose:
      - '8080'
    ports:
      - '8080:8080'
# angular
  client:
    build: .
    expose:
      - '4200'
    ports:
      - '4200:4200'